# xp-forge/json-patch

language: php

php:
  - 5.6
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - wget 'https://github.com/xp-framework/xp-runners/releases/download/v5.3.1/setup' -O - | php
  - composer install --prefer-dist
  - echo "vendor/autoload.php" > composer.pth
  - echo "use=vendor/xp-framework/core" > xp.ini
  - echo "[runtime]" >> xp.ini
  - echo "date.timezone=Europe/Berlin" >> xp.ini

script:
  - wget 'https://github.com/json-patch/json-patch-tests/archive/master.zip' -O master.zip
  - unzip master.zip && rm master.zip
  - ./unittest src/test/php -a json-patch-tests-master/
