# xp-forge/json-patch

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

before_script:
  - curl -sSL https://dl.bintray.com/xp-runners/generic/xp-run-master.sh > xp-run
  - composer install --prefer-dist
  - echo "vendor/autoload.php" > composer.pth
  - wget 'https://github.com/json-patch/json-patch-tests/archive/master.zip' -O master.zip
  - unzip master.zip && rm master.zip

script:
  - sh xp-run xp.unittest.TestRunner src/test/php -a json-patch-tests-master/
  - sh xp-run xp.measure.Runner lang.mirrors.performance.ClassParsingPerformance -n 100